micronaut:
  server:
    port: ${server.port}
    host: ${server.host}
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "file:frontend"
  application:
    name: liberty_Web
  cache:
    caffeine:
      enabled: true
      specs:
        mojang-cache:
          maximum-size: ${caffeine.mojang.maxSize}
          expires-after-write: ${caffeine.mojang.expiration}
datasources:
  default:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    hikari:
      maximumPoolSize: ${database.hikaricp.maxPoolSize}
      maxLifetime: ${database.hikaricp.maxLifetime}
      idleTimeout: ${database.hikaricp.idleTimeout}
      connectionTimeout: ${database.hikaricp.connectionTimeout}
netty:
  default:
    allocator:
      max-order: 3
