micronaut:
  server:
    port: ${server.port}
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "file:/home/great-array/IdeaProjects/Liberty_Web/FrontEnd/webroot"
  application:
    name: liberty_Web
  cache:
    caffeine:
      enabled: true
      specs:
        mojang-cache:
          maximum-size: ${caffeine.mojang.maxSize}
          expires-after-write: ${caffeine.mojang.expiration}
datasources:
  default:
    url: ${database.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.username}
    password: ${database.password}
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL
    hikari:
      maximumPoolSize: ${database.hikaricp.maxPoolSize}
      maxLifetime: ${database.hikaricp.maxLifetime}
      idleTimeout: ${database.hikaricp.idleTimeout}
      connectionTimeout: ${database.hikaricp.connectionTimeout}
netty:
  default:
    allocator:
      max-order: 3
