micronaut:
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "file:path/Liberty_Web/FrontEnd/webroot"
  application:
    name: liberty_Web
  cache:
    caffeine:
      enabled: true
      specs:
        mojang-cache:
          maximum-size: 150
          expires-after-write: 10m
datasources:
  default:
    url: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ""
    password: ""
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL
    hikari:
      maximumPoolSize: 6
netty:
  default:
    allocator:
      max-order: 3
